### ISSUE TITLE
Disconnect and connection API?

### ISSUE THREAD

**Issue by dax70** [megastef/node-crate#10]
First off, thanks for this library.

I would like to better understand the intent and usage you had in mind. I see there is a connection pulling helper object/function and a connect on the crate object. 

Should there be a way to disconnect the client gracefully?
Also in order to reuse the connection, should it return an object? 

Otherwise  each request would have to assume the server is already connected, but without a good way to see if the connection dropped, failed, etc.

**Comment by megastef** [comment]
The API is HTTP based, so there is no static TCP connection. If not already connected a new http request with a new TCP connection is made. Error handlers are thre to tell you that something failed.
